CREATE TABLE cars (
                      car_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      brand varchar(30) NOT NULL,
                      model varchar(30) NOT NULL,
                      price integer NOT NULL CHECK ( price > 0 )
);


CREATE TABLE persons (
                         person_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(80) NOT NULL UNIQUE,
                         age integer CHECK ( age > 0 ) DEFAULT 18,
                         can_drive boolean,
                         car INTEGER REFERENCES cars(car_id)
);